site_name: Cartusian Invitational
extra_css:
    - css/extra.css
theme:
    name: material
    palette:
        scheme: slate
        primary: amber
        accent: cyan
    features:
        - navigation.sections
markdown_extensions:
  - attr_list
  - md_in_html